site_name: Celeste Code Mod 教程
repo_url: https://github.com/Saplonily/CelesteModTutorial
site_description: Celeste Code Mod Tutorial
site_author: Saplonily

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/images/favicon.png
  features:
    - content.code.copy
    - content.tabs.link

extra_css:
  - css/content.css

markdown_extensions:
  - admonition # 警告
  - meta # 元数据
  - attr_list
  - md_in_html
  - def_list # 列表
  - pymdownx.tilde # 下划线
  - pymdownx.tasklist # 列表
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight: # 语法高亮
      pygments_lang_class: true
      linenums: true

nav:
  - 首页: "index.md"
  - 入门:
      - Celeste, Everest, MonoMod: "begin/celeste_everest_monomod.md"
      - 基础环境配置: "begin/basic_env.md"
      - 偏好: "begin/preference.md"
      - 钩子, 阅读代码 I: "begin/hook,reading_1.md"
      - 简单自定义实体: "begin/simple_entity.md"
      - 简单自定义Trigger: "begin/simple_trigger.md"
      - 阅读代码 II: "begin/reading_2.md"
      - 简单贴图: "begin/simple_texturing.md"
  - 过渡:
      - 更多EC: "trans/ec_common.md"
      - Alarm, Tween, Coroutine: "trans/common1.md"
      - Flag, Tag, Tracker: "trans/common2.md"
      # - Sprite, Image: "trans/common3.md"
      - IL: "trans/il.md"
      - IL 钩子与随意钩取: "trans/adv_hooks.md"
      - 协程的钩取与私有成员访问: "trans/adv_hooks2.md"
      - Session, Settings, SaveData: "trans/session_settings_savedata.md"
      # - 调试: "extra/debug.md"
  - 其他:
      - XML简单介绍: "other/xml-speedrun.md"
  - 额外 - LuaCutscene:
      - 开始: "extra_luacs/begin.md"
      - 参考: "extra_luacs/reference.md"
      - C# 交互: "extra_luacs/cs_access.md"
      - 例子: "extra_luacs/examples.md"
      # - 高级对话: "extra_luacs/advanced_dialog.md"
  - 额外 - CMCC:
      - 首页: "extra_cmcc/index.md"
      - readme: "extra_cmcc/cmcc/ReadMe.md"
      - FAQ: "extra_cmcc/cmcc/todo.md"
  - 历史归档:
    - 基础环境配置: "arc/basic_env.md"
    - 偏好-sdk-styled-proj: "arc/sdk-styled-proj.md"